services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Saalevent\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Utility/*'
      - '../Classes/Domain/Model/*'